version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: .docker/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./minerva-vault-api:/app
      - media_volume:/app/media
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE = ${DJANGO_SETTINGS_MODULE}
      - DATABASE_URL = ${DATABASE_URL}
      - DEBUG = ${DEBUG}
      - PYTHONDONTWRITEBYTECODE = ${PYTHONDONTWRITEBYTECODE}
      - PYTHONUNBUFFERED = ${PYTHONUNBUFFERED}
  web:
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./minerva-vault-web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL}

  db:
    image: postgres:17.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  media_volume: